<a href='https://www.hexnbit.com/'> <img src='https://www.hexnbit.com/wp-content/uploads/2019/09/hexnbit_final_66px.png'/> </a>

# Assignment

Mentioned below are the tasks, the solution for each tasks has to be appended by inserting a new cell below the task,
along with the following description:-
1. Why the method was used (if applicable)
2. Explanation of logic

### Task1

- Convert all characters of the word "PYTHON" to its decimal equivalent and then store them.
- Convert all the decimal equvalents back to characters 

**Hint:** Built in functions to do so are there to perform this task
Refer https://docs.python.org/3/library/functions.html

In [38]:
sample_char = 'PYTHON'
dec_val = []
for i in sample_char:
    dec_val.append(ord(i))
print(dec_val)
for j in dec_val:
    print(chr(j))
    

[80, 89, 84, 72, 79, 78]
P
Y
T
H
O
N


*** Using ascii values to convert chr into its ascii values and ord into its chr values using for loop statements to iterate in both python and list and print one by on     ***

### Task2
- Raise 2 to the power 10

In [39]:
print(2**10)

1024


-   Uisng ** operator to get raise to power

### Task3

- From the given list, starting from Japan, print alternate elements
- From the given list, print element at indexes 1,4,5,8 (**Hint**: Use for loop or list comprehension)

In [40]:
# Task 3
list1=["India", "Japan","Singapore","China","Australia","Africa","Dubai","France","Italy","Germany"]
for i in list1[1::2]:
    print(i)
print()
for j in [1,4,5,8]:
    print(list1[j])

Japan
China
Africa
France
Germany

Japan
Australia
Africa
Italy


#### Printing list by slicing method, gives them start, step values
#### make a list of desired index and iterate in that list and print coressponding values of indexes

-   Use for loop and give starting index and step size to iterate.
-   User for loop and create an list of given indexs and print list1 of j iteration.

### Task4

- From the given list, extract the "Hex" and print it

In [41]:
# Task 4
list2=[22,[4, [True, False], 6, 8], [888, 999,[111,222,["Hex"]]] ]
print(list2[2][2][2])

['Hex']


-   Concept of nesting list.
-   Travel one by one list.
-   There is more than 1 list present inside list.

### Task5

- From the given dictionary, fetch the keyword "TOPD"

In [42]:
# Task 5
dict1={"Tevatron":["Technologies","Pvt","Ltd",{"Domains":["Embedded","IoT","AI","ML"],"Projects":["inhouse","TOPD"]}]}
print(dict1['Tevatron'][3]['Projects'][1])

TOPD


###### In above problem, I got to the dictionary and there is one element and that element contain a list and that list contain a dictionary and the second key 'project' contains a list as values and list of that second element contains TOPD.

### Task6
There are 3 height categories

**167 and below  =**    Short <br>
**168 to 182     =**    Average <br>
**182 and above  =**    Tall<br>

Write a programe which gets the input from user and prints if the category the person fits in

**Hint**: Use function input()

In [43]:
persion_heightCat = int(input("Enter You height: "))
if(persion_heightCat<=167):
    print("short")
elif(182>=persion_heightCat>=168):
    print("Average")
else:
    print("Tall")

short


###### Using conditional statements to check the condition of input.

### Task7

Using maximum 2 lines of code, generate all upper case alphabets

**Hint**: Refer ASCII Table

In [44]:
for i in range(65,91):
    print(chr(i))


A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z


##### by using ascii table we can print numbers and chr without using any numbers or char in program.

### Task8

Generate integers between (100 and 200) both inclusive, using NumPy

In [45]:
import numpy as np
list_int = np.arange(100,201)
print(list_int)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]


###### Using numpy array methods to generate the an array of list.

### Task9

Print all even integers from the array created in Task8

In [46]:
j = 2
for i in list_int:
    if i%j==0:
        print(i)
    

100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
200


#### using for loop and inside for loop use conditional statements to print that values which is satisfies the even condition,\

### Task10

Print all 100 values from Standard Normal Distribution

In [47]:
Ran_Distr = np.random.standard_normal(100)
print(Ran_Distr)


[ 1.55856594 -0.48608146  0.84700227 -0.93422384 -2.23196151 -0.01954458
 -2.13384876 -1.1516951  -0.71740216  1.8291511   0.88442058 -2.8170134
 -0.67741774 -1.09228904 -0.66158868 -0.47866684  0.63626963  1.98364051
 -0.51720145  0.54645299 -0.8392153  -0.35175494  0.95651845 -1.30314694
  1.60836069  0.40111215  3.00291159 -1.06814567  0.21370294 -0.33845935
  0.34641604 -0.72090464 -0.33491502  1.5321539  -1.61828675  0.42041286
 -0.86307842  0.41295495  1.84676935  0.85272087 -1.04529013 -0.03349507
  0.46990429  0.36510118  0.79058378  0.1006683   0.35607924  1.34184235
  0.55806867 -2.17375061 -0.2643051   0.44114995  0.11478888 -0.19765182
 -1.12538569  0.16858283  1.69792929 -0.69504231  1.81031022  0.68152717
  0.11008976 -0.54093602 -1.37711993  0.34835278  0.39689819 -0.73059623
  0.4823031  -0.30297217  2.00283325  0.33361585  0.25032928 -1.34589992
  0.87603225  0.99754792  1.73726954  0.21604407  1.09590102  1.0865328
 -0.04894097  0.13136292  0.38909477 -1.23961121  1.0

###### USing standard_normal function to generate equally distributed number.

### Task11

Create a NumPy array of random number, whose dimension attribute is equal to 4

In [48]:
list_4 = np.random.random(4)
print(list_4)

[0.03699756 0.63375771 0.78217988 0.67934852]


### Task12

Create an NumPy array of 100 values evenly spaced between 10 and 20

In [49]:
array_C = np.random.randint(10,20,100) #give the range of numbers 10,20 and no. of elements is 100.
print(array_C)

[14 12 10 19 14 12 19 16 11 10 19 18 17 14 15 19 15 17 14 10 19 11 18 11
 14 17 11 15 18 17 11 18 18 11 10 13 17 18 11 19 11 11 14 18 10 18 11 19
 16 17 12 14 13 18 16 13 19 17 15 19 12 13 17 18 18 10 16 18 12 11 14 11
 14 12 17 15 13 10 18 17 14 18 18 13 10 19 14 11 13 17 11 10 19 15 17 11
 17 13 14 19]


### Task13

Create a NumPy array of shape 5x5 and print the last 3 rows

In [50]:
ara_1 = np.arange(0,25).reshape(5,5) #creating an array of elements size 25 and resahpe into 5 rows and 5 columns.

print(ara_1[2:]) #using slicing methods to print rows.by default it print rows.

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


###### Using slicing methods to print the rows

### Task14

Using the array created above in Task13, Print the first 2 columns

In [51]:
print(ara_1[0:,0:2]) # using slicing to print column


[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]


##### Using slicing methods to print column.

### Task15

Create an array of 25 random values
- Find the sum of all elements
- Print the element with maximum value and minimum value

In [52]:
rand_val = np.arange(0,25)  #Using arange function for better result instead of random.random(25).
print(rand_val)
print("\n")
print(np.sum(rand_val))
print(np.max(rand_val))
print(np.min(rand_val))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


300
24
0


### Task16

In the array created above, print columns with indexes 1,3,4 without directly indexing them <br>
**Hint:** Make use of another list for indexing

In [53]:
l = [1,3,4] #created a list of desired number for indexing
for i in l: # iterating i in list l.
    print(ara_1[0:,i]) #using slicing methods to print column.

[ 1  6 11 16 21]
[ 3  8 13 18 23]
[ 4  9 14 19 24]


### Task17
Read car_sales.csv

In [54]:
import pandas as pd
data_file = pd.read_csv("car_sales.csv") # read the file from memory.
print(data_file)


    Unnamed: 0 Manufacturer    Model     Type  Min.Price  Price  Max.Price  \
0            1        Acura  Integra    Small       12.9   15.9       18.8   
1            2        Acura   Legend  Midsize       29.2   33.9       38.7   
2            3         Audi       90  Compact       25.9   29.1       32.3   
3            4         Audi      100  Midsize       30.8   37.7       44.6   
4            5          BMW     535i  Midsize       23.7   30.0       36.2   
..         ...          ...      ...      ...        ...    ...        ...   
88          89   Volkswagen  Eurovan      Van       16.6   19.7       22.7   
89          90   Volkswagen   Passat  Compact       17.6   20.0       22.4   
90          91   Volkswagen  Corrado   Sporty       22.9   23.3       23.7   
91          92        Volvo      240  Compact       21.8   22.7       23.5   
92          93        Volvo      850  Midsize       24.8   26.7       28.5   

    MPG.city  MPG.highway             AirBags  ... Passengers L

### Task18
Sort data frame in ascending order of the Price column

In [55]:
data_file.sort_values(by=['Price'],ascending=True)  #it will sort the price column in ascending order.

Unnamed: 0   Manufacturer     Model     Type  Min.Price  Price  Max.Price  \
30          31           Ford   Festiva    Small        6.9    7.4        7.9   
43          44        Hyundai     Excel    Small        6.8    8.0        9.2   
52          53          Mazda       323    Small        7.4    8.3        9.1   
38          39            Geo     Metro    Small        6.7    8.4       10.0   
79          80         Subaru     Justy    Small        7.3    8.4        9.5   
..         ...            ...       ...      ...        ...    ...        ...   
3            4           Audi       100  Midsize       30.8   37.7       44.6   
18          19      Chevrolet  Corvette   Sporty       34.6   38.0       41.5   
10          11       Cadillac   Seville  Midsize       37.5   40.1       42.7   
47          48       Infiniti       Q45  Midsize       45.4   47.9       50.4   
58          59  Mercedes-Benz      300E  Midsize       43.8   61.9       80.0   

    MPG.city  MPG.highway             AirBags  ... Passengers Length  \
30        31           33                None  ...          4    141   
43        29           33                None  ...          5    168   
52        29           37                None  ...          4    164   
38        46           50                None  ...          4    151   
79        33           37                None  ...          4    146   
..       ...          ...                 ...  ...        ...    ...   
3         19           26  Driver & Passenger  ...          6    193   
18        17           25         Driver only  ...          2    179   
10        16           25  Driver & Passenger  ...          5    204   
47        17           22         Driver only  ...          5    200   
58        19           25  Driver & Passenger  ...          5    187   

    Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  Weight  \
30         90     63           33            26.0         12.0    1845   
43         94     63           35            26.0         11.0    2345   
52         97     66           34            27.0         16.0    2325   
38         93     63           34            27.5         10.0    1695   
79         90     60           32            23.5         10.0    2045   
..        ...    ...          ...             ...          ...     ...   
3         106     70           37            31.0         17.0    3405   
18         96     74           43             NaN          NaN    3380   
10        111     74           44            31.0         14.0    3935   
47        113     72           42            29.0         15.0    4000   
58        110     69           37            27.0         15.0    3525   

     Origin                Make  
30      USA        Ford Festiva  
43  non-USA       Hyundai Excel  
52  non-USA           Mazda 323  
38  non-USA           Geo Metro  
79  non-USA        Subaru Justy  
..      ...                 ...  
3   non-USA            Audi 100  
18      USA  Chevrolet Corvette  
10      USA    Cadillac Seville  
47  non-USA        Infiniti Q45  
58  non-USA  Mercedes-Benz 300E  

[93 rows x 28 columns]

###### using sort methods to sort by values.

### Task19
Print number of unique car manufacturers in the data

In [56]:
data_file.drop_duplicates(subset="Manufacturer") # it drop the duplicate values of manufacturer column.


Unnamed: 0   Manufacturer        Model     Type  Min.Price  Price  \
0            1          Acura      Integra    Small       12.9   15.9   
2            3           Audi           90  Compact       25.9   29.1   
4            5            BMW         535i  Midsize       23.7   30.0   
5            6          Buick      Century  Midsize       14.2   15.7   
9           10       Cadillac      DeVille    Large       33.0   34.7   
11          12      Chevrolet     Cavalier  Compact        8.5   13.4   
19          20       Chrylser     Concorde    Large       18.4   18.4   
20          21       Chrysler      LeBaron  Compact       14.5   15.8   
22          23          Dodge         Colt    Small        7.9    9.2   
28          29          Eagle       Summit    Small        7.9   12.2   
30          31           Ford      Festiva    Small        6.9    7.4   
38          39            Geo        Metro    Small        6.7    8.4   
40          41          Honda      Prelude   Sporty       17.0   19.8   
43          44        Hyundai        Excel    Small        6.8    8.0   
47          48       Infiniti          Q45  Midsize       45.4   47.9   
48          49          Lexus        ES300  Midsize       27.5   28.0   
50          51        Lincoln  Continental  Midsize       33.3   34.3   
52          53          Mazda          323    Small        7.4    8.3   
57          58  Mercedes-Benz         190E  Compact       29.0   31.9   
59          60        Mercury        Capri   Sporty       13.3   14.1   
61          62     Mitsubishi       Mirage    Small        7.7   10.3   
63          64         Nissan       Sentra    Small        8.7   11.8   
67          68     Oldsmobile      Achieva  Compact       13.0   13.5   
71          72       Plymouth        Laser   Sporty       11.4   14.4   
72          73        Pontiac       LeMans    Small        8.2    9.0   
77          78           Saab          900  Compact       20.3   28.7   
78          79         Saturn           SL    Small        9.2   11.1   
79          80         Subaru        Justy    Small        7.3    8.4   
82          83         Suzuki        Swift    Small        7.3    8.6   
83          84         Toyota       Tercel    Small        7.8    9.8   
87          88     Volkswagen          Fox    Small        8.7    9.1   
91          92          Volvo          240  Compact       21.8   22.7   

    Max.Price  MPG.city  MPG.highway             AirBags  ... Passengers  \
0        18.8        25           31                None  ...          5   
2        32.3        20           26         Driver only  ...          5   
4        36.2        22           30         Driver only  ...          4   
5        17.3        22           31         Driver only  ...          6   
9        36.3        16           25         Driver only  ...          6   
11       18.3        25           36                None  ...          5   
19       18.4        20           28  Driver & Passenger  ...          6   
20       17.1        23           28  Driver & Passenger  ...          6   
22       10.6        29           33                None  ...          5   
28       16.5        29           33                None  ...          5   
30        7.9        31           33                None  ...          4   
38       10.0        46           50                None  ...          4   
40       22.7        24           31  Driver & Passenger  ...          4   
43        9.2        29           33                None  ...          5   
47       50.4        17           22         Driver only  ...          5   
48       28.4        18           24         Driver only  ...          5   
50       35.3        17           26  Driver & Passenger  ...          6   
52        9.1        29           37                None  ...          4   
57       34.9        20           29         Driver only  ...          5   
59       15.0        23           26         Driver only  ...          4  

### Task20
Print the maximum Wheelbase from the data

In [57]:
print(data_file['Wheelbase'].max()) #It will gives max values of that column name.

119


### Task21
Print the car Model which has maximum Wheelbase

In [58]:
i = data_file['Wheelbase'].idxmax() #it gives index corressponding to that row.
print(data_file['Model'][i]) # Finding the model at corresponding index.

Aerostar


### Task22

Print the Details of car with maximum passenger capacity

In [59]:
i = data_file["Passengers"].idxmax() #finding index of max passangers in columns. and printing corresponding to that column.
data_file.loc[i] #printing deatils of that car with max passanger

Unnamed: 0                         17
Manufacturer                Chevrolet
Model                           Astro
Type                              Van
Min.Price                        14.7
Price                            16.6
Max.Price                        18.6
MPG.city                           15
MPG.highway                        20
AirBags                          None
DriveTrain                        4WD
Cylinders                           6
EngineSize                        4.3
Horsepower                        165
RPM                              4000
Rev.per.mile                     1790
Man.trans.avail                    No
Fuel.tank.capacity               27.0
Passengers                          8
Length                            194
Wheelbase                         111
Width                              78
Turn.circle                        42
Rear.seat.room                   33.5
Luggage.room                      NaN
Weight                           4025
Origin      